version: "3.9"

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - PROGRAM=${PROGRAM}
      - ARGS=${ARGS}
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - RUST_LOG=debug
    volumes:
      - ./data:/app/data
    restart: always
